name: Build 
on:
  push:
    branches:
      - 'main'

jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.repo_name }}/${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tag }} 
          cache-from: type=registry,ref={{ steps.meta.outputs.tags }}
          cache-to: type=inline
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  Deploy: # job name
    needs: push-image-to-docker-hub
    runs-on: ubuntu-latest   
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - name: checkout
      uses: actions/checkout@v1
      # Runs a set of commands using the runners shell
    - name: deploy source-code
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        source: "*"
        target: "tmp/counter-service"
    - name: run remote ssh commands to install helm 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        script: |
          cd /tmp/counter-service
          helm install counter-service ./counter-chart

